parent(jack,joe).
parent(jack,karl).
parent(marie,anne).
parent(joe,anne).
parent(marie,paul).
parent(joe,paul).
parent(marie,sylvie).
parent(bruno,sylvie).
parent(anne,zach).
parent(tim,zach).
parent(sam,tim).
parent(emma,tim).
parent(josee,sam).
parent(gilles,sam).
homme(karl).
homme(jack).
homme(joe).
femme(marie).
femme(sylvie).
femme(anne).
homme(bruno).
homme(paul).
homme(tim).
homme(zach).
homme(sam).
femme(emma).
homme(gilles).
femme(josee).

gmp(X,Y):- femme(X), parent(Z,Y), homme(Z), parent(X,Z).
